language: python
python:
  - "3.6.7"

env:
  - CODECOV_TOKEN="39325344-cd5a-42b1-9925-d79a79fc43d9"

notifications:
  email: false
  
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests

# run pytest and coveralls script
script:
  - pytest --cov=app tests/

# then post the results to coveralls
after_success:
  - coveralls
  - codecov